services:
  mariadb:
    image: mariadb:latest
    container_name: db_container_salgend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salgend_pause
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
