services:
  mysql-db:
    image: mysql:8.0
    container_name: salgend_pause_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-salgend_pause}
      MYSQL_USER: ${MYSQL_USER:-salgend_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-salgend_pass}
      MYSQL_CHARSET: ${MYSQL_CHARSET:-utf8mb4}
      MYSQL_COLLATION: ${MYSQL_COLLATION:-utf8mb4_unicode_ci}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 10s
    networks:
      - salgend_network

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: salgend_pause_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      PMA_ABSOLUTE_URI: http://localhost:${PHPMYADMIN_PORT:-8081}/
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - salgend_network

volumes:
  mysql_data:
    driver: local

networks:
  salgend_network:
    driver: bridge 